version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - slam-network
    volumes:
      - slambook-vol:/var/lib


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: aWelcome@123
      MYSQL_DATABASE: user_info
      MYSQL_USER: amittashok
      MYSQL_PASSWORD: aWelcome@123
    ports:
      - "3306:3306"
    networks:
      - slam-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql

networks:
  slam-network:
    driver: bridge

volumes:
  mysql_data:
  slambook-vol:

