name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Slam-book/Dockerfile
        push: true
        tags: amittashok/slambook-cicd:latest
        cache-from: type=registry,ref=amittashok/slambook-cicd:cache
        cache-to: type=registry,ref=amittashok/slambook-cicd:cache,mode=max

    - name: Log out from Docker Hub
      run: docker logout

